const STANDARD_WORDS = [
    { dataid: '153', datacontent: 'Minutes', language: 'en' },
    { dataid: '153', datacontent: 'Protokoll', language: 'de' },
    { dataid: '156', datacontent: 'Opening of sitting', language: 'en' },
    { dataid: '156', datacontent: 'Eröffnung der Sitzung', language: 'de' },
    { dataid: '159', datacontent: '(debate)', language: 'en' },
    { dataid: '159', datacontent: '(Aussprache)', language: 'de' },
    { dataid: '1004', datacontent: 'Council and Commission statements:', language: 'en' },
    { dataid: '1004', datacontent: 'Erklärungen des Rates und der Kommission:', language: 'de' },
    { dataid: '1006', datacontent: 'made the statements', language: 'en' },
    { dataid: '1006', datacontent: 'geben die Erklärungen ab}}.', language: 'de' },
    { dataid: '140', datacontent: 'IN THE CHAIR:', language: 'en' },
    { dataid: '140', datacontent: 'VORSITZ:', language: 'de' },
    { dataid: '1007', datacontent: 'The following spoke:', language: 'en' },
    { dataid: '1007', datacontent: 'Es sprechen:', language: 'de' },
    {
        dataid: '168',
        datacontent: 'Motion for a resolution to wind up the debate tabled under Rule 132(2)',
        language: 'en',
    },
    {
        dataid: '168',
        datacontent: 'Zum Abschluss der Aussprache gemäß Artikel 132 Absatz 2 GO eingereichter Entschließungsantrag:',
        language: 'de',
    },
    { dataid: '169', datacontent: 'Vote', language: 'en' },
    { dataid: '169', datacontent: 'Abstimmung', language: 'de' },
    { dataid: '1009', datacontent: 'introduced the report', language: 'en' },
    { dataid: '1009', datacontent: 'erläutert den Bericht', language: 'de' },
    { dataid: '180', datacontent: 'Agenda', language: 'en' },
    { dataid: '180', datacontent: 'Dokument \„Tagesordnung\“', language: 'de' },
    { dataid: '1465', datacontent: 'Rule146(1)', language: 'en' },
    { dataid: '145', datacontent: 'Rule145(1)', language: 'en' },
    { dataid: '187', datacontent: 'referred to responsible', language: 'en' },
    { dataid: '187', datacontent: 'Ausschussbefassung federführend', language: 'de' },
    { dataid: '188', datacontent: 'opinion', language: 'en' },
    { dataid: '188', datacontent: 'mitberatend', language: 'de' },
    { dataid: '189', datacontent: 'on', language: 'en' },
    { dataid: '189', datacontent: 'zur', language: 'de' },
    {
        dataid: '190',
        datacontent: "The agenda of the next day's sitting had been established",
        language: 'en',
    },
    {
        dataid: '190',
        datacontent: "Die Tagesordnung für die Sitzung am folgenden Tag ist festgelegt",
        language: 'de',
    },
    { dataid: '191', datacontent: 'The following documents had been received', language: 'en' },
    { dataid: '191', datacontent: 'Folgende Dokumente sind eingegangen', language: 'de' },
    { dataid: '192', datacontent: 'from other institutions', language: 'en' },
    { dataid: '192', datacontent: 'von anderen Organen}', language: 'de' },
    { dataid: '193', datacontent: 'The President would consult the', language: 'en' },
    { dataid: '193', datacontent: 'GO wird der Präsident zu diesem', language: 'de' },
    { dataid: '194', datacontent: 'and the', language: 'en' },
    { dataid: '194', datacontent: 'und den', language: 'de' },
    { dataid: '195', datacontent: 'on this proposal, in accordance with', language: 'en' },
    { dataid: '196', datacontent: 'Rapporteur', language: 'en' },
    { dataid: '196', datacontent: 'Berichterstatterin', language: 'de' },
    { dataid: '197', datacontent: 'and', language: 'en' },
    { dataid: '197', datacontent: 'und', language: 'de' },
    { dataid: '198', datacontent: 'konsultieren', language: 'de' },
];
export default STANDARD_WORDS;
