const LIST_OF_SPEAKERS = [
    {
        id: 1,
        fullName: 'Ursula von der leyen (President of the Cpmmission)',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
    },
    {
        id: 2,
        fullName: 'Caroline Voaden',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
    },
    {
        id: 3,
        fullName: 'Jude Kirton-Darling',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: true,
        isBlueCardSpeaker: false,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: 'PPE',
    },
    {
        id: 4,
        fullName: 'Antonio Tajani (PPE)',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: true,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
    },
    {
        id: 5,
        fullName: 'Christian Allard (PPE)',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
    },
];
export default LIST_OF_SPEAKERS;
