const LIST_OF_SPEAKERS = { 
    'en': [
    {
        id: 1,
        fullName: 'Ursula von der Leyen',
        additionalDescription: ' (President of the Commission)',
        additionalDescriptionDisplay: '(President of the Commission)',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T09:48:00',
    },
    {
        id: 2,
        fullName: 'Caroline Voaden',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T09:55:00',
    },
    {
        id: 3,
        fullName: 'Jude Kirton-Darling',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T09:59:00',
    },
    {
        id: 4,
        fullName: 'Antonio Tajani',
        additionalDescription: ', Chair of the Committee on Constitutional Affairs',
        additionalDescriptionDisplay: 'Chair of the Committee on Constitutional Affairs',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: true,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T10:05:00',
    },
    {
        id: 5,
        fullName: 'Christian Allard',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: 'accepted',
        blueCardName: 'fdf',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T10:12:00',
    },
    {
        id: 6,
        fullName: 'Andrej Plenković',
        additionalDescription: ' (President-in-Office of the Council)',
        additionalDescriptionDisplay: '(President-in-Office of the Council)',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T10:23:00',
    },
    {
        id: 7,
        fullName: 'Hermann Tertsch',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T10:28:00',
    },
    {
        id: 8,
        fullName: 'Geoffrey Van Orden',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: true,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T10:39:00',
    },
    {
        id: 9,
        fullName: "Guy Verhofstadt, Parliament's Brexit coordinator",
        additionalDescription: ", Parliament's Brexit coordinator",
        additionalDescriptionDisplay: "Parliament's Brexit coordinator",
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T10:47:00',
    },
    {
        id: 11,
        fullName: 'Manfred Weber',
        additionalDescription: ', President of the PPE Group',
        additionalDescriptionDisplay: 'President of the PPE Group',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T10:54:00',
    },
    {
        id: 12,
        fullName: 'Iratxe García Pérez',
        additionalDescription: ', President of the S&D Group',
        additionalDescriptionDisplay: 'President of the S&D Group',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T11:05:00',
    },
    {
        id: 13,
        fullName: 'Dacian Cioloş',
        additionalDescription: ', President of the Renew Group',
        additionalDescriptionDisplay: 'President of the Renew Group',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T11:14:00',
    },
    {
        id: 14,
        fullName: 'Philippe Lamberts',
        additionalDescription: ', Co-President of the Verts/ALE Group',
        additionalDescriptionDisplay: 'Co-President of the Verts/ALE Group',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T11:17:00',
    },
    {
        id: 15,
        fullName: 'Isabel Wiseler-Lima',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T11:22:00',
    },
    {
        id: 16,
        fullName: 'Mairead McGUINNESS',
        additionalDescription: ', Vice-President',
        additionalDescriptionDisplay: 'Vice-President',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T11:29:00',
    }, ],
    'de': [
    {
        id: 1,
        fullName: 'Ursula von der Leyen',
        additionalDescription: ' (Präsidentin der Kommission)',
        additionalDescriptionDisplay: '(Präsidentin der Kommission)',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T11:35:00',
    },
    {
        id: 2,
        fullName: 'Caroline Voaden',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T11:44:00',
    },
    {
        id: 3,
        fullName: 'Jude Kirton-Darling',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T11:51:00',
    },
    {
        id: 4,
        fullName: 'Antonio Tajani',
        additionalDescription: ', Chair of the Committee on Constitutional Affairs',
        additionalDescriptionDisplay: 'Chair of the Committee on Constitutional Affairs',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: true,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T11:57:00',
    },
    {
        id: 5,
        fullName: 'Christian Allard',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: 'accepted',
        blueCardName: 'fdf',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T11:59:00',
    },
    {
        id: 6,
        fullName: 'Andrej Plenković',
        additionalDescription: ' (amtierender Ratsvorsitzender)',
        additionalDescriptionDisplay: '(amtierender Ratsvorsitzender)',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T12:05:00',
    },
    {
        id: 7,
        fullName: 'Hermann Tertsch',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T12:07:00',
    },
    {
        id: 8,
        fullName: 'Geoffrey Van Orden',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: true,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T12:12:00',
    },
    {
        id: 9,
        fullName: "Guy Verhofstadt",
        additionalDescription: ', Brexit-Koordinator des EP',
        additionalDescriptionDisplay: 'Brexit-Koordinator des EP',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T12:19:00',
    },
    {
        id: 11,
        fullName: 'Manfred Weber',
        additionalDescription: ', Vorsitzender der PPE-Fraktion',
        additionalDescriptionDisplay: 'Vorsitzender der PPE-Fraktion',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T12:26:00',
    },
    {
        id: 12,
        fullName: 'Iratxe García Pérez',
        additionalDescription: ', Vorsitzende der S&D-Fraktion',
        additionalDescriptionDisplay: 'Vorsitzende der S&D-Fraktion',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T12:30:00',
    },
    {
        id: 13,
        fullName: 'Dacian Cioloş',
        additionalDescription: ', Vorsitzender der Renew-Frakion',
        additionalDescriptionDisplay: 'Vorsitzender der Renew-Frakion',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T12:32:00',
    },
    {
        id: 14,
        fullName: 'Philippe Lamberts',
        additionalDescription: ', Kovorsitzende der Verts/ALE-Fraktion',
        additionalDescriptionDisplay: 'Kovorsitzende der Verts/ALE-Fraktion',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'male',
        time: '2020-01-14T12:38:00',
    },
    {
        id: 15,
        fullName: 'Isabel Wiseler-Lima',
        additionalDescription: '',
        additionalDescriptionDisplay: '',
        title: false,
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T12:48:00',
    },
    {
        id: 16,
        fullName: 'Mairead McGUINNESS',
        additionalDescription: ', Vizepräsidentin',
        additionalDescriptionDisplay: 'Vizepräsidentin',
        title: false,
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
        gender: 'female',
        time: '2020-01-14T12:54:00',
    }, ]
};
export default LIST_OF_SPEAKERS;
