const LIST_OF_SPEAKERS = [
    {
        id: 1,
        fullName: 'Ursula von der Leyen (President of the Cpmmission)',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
    {
        id: 2,
        fullName: 'Caroline Voaden',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
    },
    {
        id: 3,
        fullName: 'Jude Kirton-Darling',
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
    {
        id: 4,
        fullName: 'Antonio Tajani, Chair of the Committee on Constitutional Affairs',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: true,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
    },
    {
        id: 5,
        fullName: 'Christian Allard',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: 'accepted',
        blueCardName: 'fdf',
        behalfOfGroup: '',
    },
    {
        id: 6,
        fullName: 'Andreij Plenkovic (President-in-Office of the Council)',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
    {
        id: 7,
        fullName: 'Hermann Tertsch',
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
    {
        id: 8,
        fullName: 'Geoffrey Van Orden',
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: true,
        blueCardStatus: 'declined',
        blueCardName: 'fdf',
        behalfOfGroup: '',
    },
    {
        id: 9,
        fullName: "Guy Verhofstadt, Parliament's Brexit coordinator",
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
    {
        id: 11,
        fullName: 'Manfred Weber, President of the PPE Group',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
    {
        id: 12,
        fullName: 'Iratxe Garcia Perez, President of the S&D Group',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
    {
        id: 13,
        fullName: 'Dacian Ciolo?, President of the Renew Group',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
    {
        id: 14,
        fullName: 'Philippe Lamberts , Co-President of the Verts/ALE Group',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
    {
        id: 15,
        fullName: 'Isabel Wiseler-Lima',
        hasDisplayFunction: false,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
    {
        id: 16,
        fullName: 'Mairead McGUINNESS, Vice-President',
        hasDisplayFunction: true,
        hasOnBehalfOfGroup: false,
        isBlueCardSpeaker: false,
        blueCardStatus: '',
        blueCardName: '',
        behalfOfGroup: '',
    },
];
export default LIST_OF_SPEAKERS;
